sudo: required
language: node_js
node_js:
  - "0.8"
  - "0.10"

before_script:
  - "npm install -g jshint"
  - "curl -L http://git.io/ejPSng | /bin/sh"

script:
  - "node start_test.js"
  - "jshint ./"
